---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: places
  labels:
    component: places
spec:
  replicas: 1
  selector:
    matchLabels:
      component: places
spec:
  template:
    metadata:
      labels:
        component: places
    spec:
      containers:
        - name: places-dev
          image: mgajic91/places/places:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
          - name: JAVA_OPTS
            value: "-Xmx1g -XX:+UseCompressedOops"
          resources:
            limits:
              memory: "1Gi"
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always
